// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcThWtB77nGBZQndK5hBhAhwv-gqEZfa0',
    appId: '1:473089857358:web:28cd795c1870e53926701f',
    messagingSenderId: '473089857358',
    projectId: 'nutrisis-fd647',
    authDomain: 'nutrisis-fd647.firebaseapp.com',
    databaseURL: 'https://nutrisis-fd647-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrisis-fd647.appspot.com',
    measurementId: 'G-XNQ8KF09MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDzg1uuDORczv_bOH14O8LsdETv1am0Qg',
    appId: '1:473089857358:android:6cbb467dbd3fe16d26701f',
    messagingSenderId: '473089857358',
    projectId: 'nutrisis-fd647',
    databaseURL: 'https://nutrisis-fd647-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrisis-fd647.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_oAsHiUbf2bjddEQmww8Ia50rOlj4wFQ',
    appId: '1:473089857358:ios:2040ba63cb22e0a126701f',
    messagingSenderId: '473089857358',
    projectId: 'nutrisis-fd647',
    databaseURL: 'https://nutrisis-fd647-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrisis-fd647.appspot.com',
    iosClientId: '473089857358-68mbk337vcjv0c542494v1qhfs5hkk3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrisys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_oAsHiUbf2bjddEQmww8Ia50rOlj4wFQ',
    appId: '1:473089857358:ios:2040ba63cb22e0a126701f',
    messagingSenderId: '473089857358',
    projectId: 'nutrisis-fd647',
    databaseURL: 'https://nutrisis-fd647-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutrisis-fd647.appspot.com',
    iosClientId: '473089857358-68mbk337vcjv0c542494v1qhfs5hkk3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrisys',
  );
}
